name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: List directories
      run: |
        pwd
        ls -R
    - name: Run tests
      run: |
        pip install pytest pytest-html
        pytest tests/ --html=test-results/report.html --self-contained-html
    - name: Archive tests results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
  
  build:
    needs: test
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
    - name: Build and Push Docker image
      env:
        DOCKER_USERNAME: ${secrets.DOCKER_USERNAME}
        DOCKER_PASSWORD: ${secrets.DOCKER_PASSWORD}
      run: |
        docker build -t my-app/spiros-model-registry:latest .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push my-app/spiros-model-registry:latest
